[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"


[project]
version = "0.0"
name = "test-django-project"


[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["test_django_project*"]
